# Generated by Django 2.1.1 on 2018-09-09 21:30

from django.db import migrations, models
import multi_tenant_system.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('entry_timestamp', models.IntegerField(default=multi_tenant_system.utils.get_current_utc_timestamp)),
                ('is_active', models.BooleanField(default=True)),
                ('max_members', models.IntegerField(default=10)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
