# Generated by Django 2.1.1 on 2018-09-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
